site:
  title: Alles-und-Nichts.com / Docs / Full
  url: http://localhost:9000
  start_page: kobol-docs::index.adoc
content:
  branches: HEAD
  sources:
  - url: ../kobol
    start_path: docs
  - url: ../kobol-docs-ui-bundle
    start_path: docs
  - url: ../jenkins
    start_path: docs
  - url: ../prometheus-grafana
    start_path: docs
  - url: ../rundeck
    start_path: docs
  - url: ../v-kube-cluster
    start_path: docs
  - url: ../pi-farm
    start_path: docs
asciidoc:
  attributes:
    kroki-server-url: http://localhost:9001
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: ../kobol-docs-ui-bundle/target/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ../kobol-docs-ui-bundle/src/main/ui-bundle/supplemental_ui/header
output:
    clean: true
    dir: ./target/public
runtime:
  cache_dir: ./target/cache/antora
  fetch: true
